---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/as-code-meetup
  children:
  - name: rancherHome
    type: udm.Environment
    members:
    - Infrastructure/as-code-meetup/myrancher/default
    - Infrastructure/as-code-meetup/myrancher
